### PR TITLE
Integrate secure ION buffer into CDMI service to implement SDP

### PR DESCRIPTION
**Pull request by ajutras-linaro**

### CODE REVIEW

**Review by petegriffin — CHANGES_REQUESTED** [review]
Could you be more verbose in the commit message about what works after this commit and how it was tested?

I can see code for obtaining the file descriptor of the secure buffer, but does this get propagated down to being registered with the TA? I'm guessing yes, but can't see where that is happening. Also looks like we would require some changes to the playready MediaKeySession Decrypt() class in playready/source/cdmi/mediakeysession.cpp to make use of the file descriptor?

**Comment by andrey-konovalov** [comment]
According to cdmi/service.cpp there could be several media engine sessions at the same time:
vector<IMediaEngineSession *> g_mediaEngineSessions;

rpc_open_cdm_mediaengine_1_svc() starts decryptShmem() as a thread passing it the index in the g_mediaEngineSessions vector, and exits immediately. So another decryptShmem() could be started for a new media engine session before the previous one finishes.

Do we ever consider two decryption threads running in parallel? If yes, then a mechanism to associate the SecureFileDescriptor with the media engine session is needed.

**Comment by ajutras-linaro** [comment]
@petegriffin, I will improve the commit messages. 

@petegriffin, yes, the file descriptor is propagated to the CMediaKeySession::Decrypt() API in PlayReady CDMI. Note that the TA actually gets a virtual address to the secure buffer as defined by the OP-TEE SDP extension. There are review requests on the playready and optee-playready repositories but I just found out that I forgot to add people to the reviewer list. Please refer to our private Gerrit server. 

@andrey-konovalov, I assumed that we want to support single session only. This may be an invalid assumption. Your comment is definitely valid. The question is should we implement this improvement or can we postpone it?

**Comment by andrey-konovalov** [comment]
@ajutras-linaro guess it depends on what this SDP prototype implementation will be used for. If it is to demonstrate that SDP is doable and can operate on some board (and your method to pass the ion buffer between different process will not be used for anything else), then limiting cdmiservice to just one media engine session is OK. If the proposed method to pass the secure buffer fd from one process to another will be used in future development (when one session limitation in cdmiservice is likely to become an issue) we should probably design the programming interface w/o this limitation from the beginning

**Comment by andrey-konovalov** [comment]
@ajutras-linaro I mean that if the current single-session implementation can be easily extended to handle multiple media engine sessions, then having it to support single session only for now is OK. If supporting multiple sessions would require interface changes (what functions to call and their args; or if your (currently static) functions would require access to m.e.session private data etc), then this should be addressed now.

**Comment by andrey-konovalov** [comment]
@ajutras-linaro maybe just more verbose commit message would suffice :)

**Review by psivasubramanian — COMMENTED** [review]
LGTM

**Comment by ajutras-linaro** [comment]
In order to support multi session, I shared a socket channel unique ID through RPC and I appended the unique ID to the socket address. Therefore, there is dedicated socket connection for each session. These changes will be available in the next patch set which I am planning to deliver by the end of the week.

**Comment by ajutras-linaro** [comment]
I provided another set of commits to take your comments into account.

**Review by petegriffin — APPROVED** [review]

**Comment by petegriffin** [comment]
Looks good to me

**Pull request merged**
